package main

func main() {
	// Uncomment the function you want to run

	// functions()
	// vars()
	// forLoop()
	// ifElse()
	// packages()
	// switches()
	// defers()
	// pointers()
	// structs()
	// runes()
	// arrays()
	// mainSlices()
	// mapsInfo()
	// methods()
	// interfaces()
	// stringer()
	// enums()
	// structEmbedding()
	// generics()
	// iterators()
	// errorHandling()
	// customErrors()
	// readers()
	// rot13reader()
	// picSlices()
	// images()
	// goroutines()
	// channels()
	// channelBuffering()
	channelSync()
}