package main

func main() {
	// Uncomment the function you want to run

	// functions()
	// vars()
	// forLoop()
	// ifElse()
	// switches()
	// defers()
	// pointers()
	// structs()
	// runes()
	// arrays()
	// slicesInfo()
	// mapsInfo()
	// methods()
	// errorHandling()
	// customErrors()
	// goroutines()
	// timers()
	// tickers()
	// workerPools()
	// waitGroups()
	// rateLimiting()
	// atomicCounters()
	// mutexes()
	// statefulGoroutines()
	// sorting()
	// sortingByFunctions()	
	// panics()
	// advancedDefers()
	// recovers()
	stringFns()	
}